apiVersion: apps/v1
kind: Deployment
metadata:
  name:	raw-store-infraestructures-prod
  namespace: icat-prod-ingestors
spec:
  replicas: 10
  selector:
    matchLabels:
      app: raw-store-infraestructures-prod
  strategy:
    type: Recreate
  template:
    metadata:
        labels:
            app: raw-store-infraestructures-prod
    spec:
      containers:
        - name: raw-store-infraestructures-prod
          image: 853583158095.dkr.ecr.eu-west-1.amazonaws.com/ecr-library-hbase-raw-ingestor:prod
          command: ["python3", "__main__.py", "-db", "cassandra"]
          #command: ["/bin/sh", "-ec", "sleep 1000"]
          env:
            - name: CONF_FILE
              value: "config.json"
          volumeMounts:
          - name: raw-store-secret
            mountPath: /app/config.json
            subPath: config.json
          - name: kafka-secret
            mountPath: /app/kafka_ca_server.crt
            subPath: kafka_ca_server.crt
          - name: kafka-secret
            mountPath: /app/kafka_ca_user.crt
            subPath: kafka_ca_user.crt
          - name: kafka-secret
            mountPath: /app/kafka_key_user.key
            subPath: kafka_key_user.key

          - name: kafka-secret-ovh
            mountPath: /app/kafka_ca_server-ovh.crt
            subPath: kafka_ca_server.crt
          - name: kafka-secret-ovh
            mountPath: /app/kafka_ca_user-ovh.crt
            subPath: kafka_ca_user.crt
          - name: kafka-secret-ovh
            mountPath: /app/kafka_key_user-ovh.key
            subPath: kafka_key_user.key
      volumes:
        - name: raw-store-secret
          secret:
            secretName: raw-store-secret
            items:
            - key: config.json
              path: config.json
        - name: kafka-secret
          secret:
            secretName: kafka-secret
            items:
              - key: kafka_ca_server.crt
                path: kafka_ca_server.crt
              - key: kafka_ca_user.crt
                path: kafka_ca_user.crt
              - key: kafka_key_user.key
                path: kafka_key_user.key
        - name: kafka-secret-ovh
          secret:
            secretName: kafka-secret-ovh
            items:
              - key: kafka_ca_server.crt
                path: kafka_ca_server.crt
              - key: kafka_ca_user.crt
                path: kafka_ca_user.crt
              - key: kafka_key_user.key
                path: kafka_key_user.key

# kubectl create secret generic raw-store-secret --from-file=config.json=config_aws.json -n icat-prod-ingestors
# kubectl create secret generic kafka-secret --from-file=kafka_ca_server.crt=/Users/eloigabal/kafka2/ca.crt --from-file=kafka_ca_user.crt=/Users/eloigabal/kafka2/user.crt --from-file=kafka_key_user.key=/Users/eloigabal/kafka2/user.key -n icat-prod-ingestors
# kubectl create secret generic kafka-secret-ovh --from-file=kafka_ca_server.crt=/Users/eloigabal/kafka/ca.crt --from-file=kafka_ca_user.crt=/Users/eloigabal/kafka/user_admin/user.crt --from-file=kafka_key_user.key=/Users/eloigabal/kafka/user_admin/user.key -n icat-prod-ingestors
