apiVersion: apps/v1
kind: Deployment
metadata:
  name:	raw-store-cassandra-infraestructures
  namespace: raw-store
spec:
  replicas: 10
  selector:
    matchLabels:
      app: raw-store-cassandra-infraestructures
  strategy:
    type: Recreate
  template:
    metadata:
        labels:
            app: raw-store-cassandra-infraestructures
    spec:
      hostAliases:
        - ip: "10.0.88.76"
          hostnames:
            - "master1.internal"
        - ip: "10.0.87.95"
          hostnames:
            - "master2.internal"
        - ip: "10.0.88.132"
          hostnames:
            - "worker1.internal"
        - ip: "10.0.86.33"
          hostnames:
            - "worker2.internal"
        - ip: "10.0.87.145"
          hostnames:
            - "worker3.internal"
        - ip: "10.0.86.214"
          hostnames:
            - "worker4.internal"
        - ip: "10.0.129.220"
          hostnames:
            - "kafka1.internal"
        - ip: "10.0.88.175"
          hostnames:
            - "database1-vpn"
        - ip: "10.0.88.151"
          hostnames:
            - "database2-vpn"
        - ip: "10.0.87.50"
          hostnames:
            - "database3-vpn"
        - ip: "10.0.88.152"
          hostnames:
            - "druid-1.internal"
      containers:
        - name: raw-store-cassandra-infraestructures
          image: 1l41bgc7.c1.gra9.container-registry.ovh.net/library/hbase_raw_ingestor:new_kafka
          command: ["python3", "__main__.py", "-db", "cassandra"]
          #command: ["/bin/sh", "-ec", "sleep 1000"]
          env:
            - name: CONF_FILE
              value: "config.json"
          volumeMounts:
          - name: raw-store-secret-cassandra
            mountPath: /app/config.json
            subPath: config.json
          - name: kafka-secret
            mountPath: /app/kafka_ca_server.crt
            subPath: kafka_ca_server.crt
          - name: kafka-secret
            mountPath: /app/kafka_ca_user.crt
            subPath: kafka_ca_user.crt
          - name: kafka-secret
            mountPath: /app/kafka_key_user.key
            subPath: kafka_key_user.key
      imagePullSecrets:
        - name: odin1pullsecret
      volumes:
        - name: raw-store-secret-cassandra
          secret:
            secretName: raw-store-secret-cassandra
            items:
            - key: config.json
              path: config.json
        - name: kafka-secret
          secret:
            secretName: kafka-secret
            items:
              - key: kafka_ca_server.crt
                path: kafka_ca_server.crt
              - key: kafka_ca_user.crt
                path: kafka_ca_user.crt
              - key: kafka_key_user.key
                path: kafka_key_user.key

# kubectl create secret generic raw-store-secret-cassandra --from-file=config.json=config_cassandra.json -n raw-store
# kubectl create secret generic kafka-secret --from-file=kafka_ca_server.crt=/Users/eloigabal/Downloads/clipboard.txt --from-file=kafka_ca_user.crt=/Users/eloigabal/Downloads/clipboard\ \(1\).txt --from-file=kafka_key_user.key=/Users/eloigabal/Downloads/clipboard\ \(2\).txt -n raw-store
